apiVersion: skaffold/v2beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-init/*
      - ./infra/k8s-dev/*
      - ./infra/k8s/*
    # flags:
    #   # additional flags passed on every command, both apply and delete.
    #   global:
    #   - --namespace=acss
build:
  local:
    push: false
  artifacts:
    # patients
    - image: insidedocker/patients
      context: services/patients
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # devices
    - image: insidedocker/devices
      context: services/devices
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # # system
    # - image: insidedocker/system
    #   context: services/system
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # # system-web
    # - image: insidedocker/system-web
    #   context: services/system-web
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.*"
    #         dest: .
    #       - src: "pages/**/*.*"
    #         dest: .
    #       - src: "public/**/*.*"
    #         dest: .
    #       - src: "styles/**/*.*"
    #         dest: .
    # # admin-web
    # - image: insidedocker/admin-web
    #   context: services/admin-web
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.*"
    #         dest: .
    #       - src: "pages/**/*.*"
    #         dest: .
    #       - src: "public/**/*.*"
    #         dest: .
    #       - src: "styles/**/*.*"
    #         dest: .


