{
 "title": "Panda",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ingress",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_instance=\"ingress-nginx\"}"
    }
   ]
  },
  {
   "title": "Devices DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  \"versionKey\"\nFROM \"Patients\"\nWHERE\n  $__timeFilter(\"createdAt\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Api logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{system=\"panda\"} | json | domain=\"API\""
    }
   ]
  },
  {
   "title": "Patients DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"createdAt\" AS \"time\",\n  \"versionKey\"\nFROM \"Patients\"\nWHERE\n  $__timeFilter(\"createdAt\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Event logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{system=\"panda\"} | json | domain=\"EVENT\""
    }
   ]
  },
  {
   "title": "System logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 5, "x": 19, "y": 16 },
   "targets": [
    {
     "expr": "{system=\"panda\"} | json | domain=\"SYSTEM\" | line_format \"{{.level}} {{.hostname}} {{.msg}}\""
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{system=\"panda\"}"
    }
   ]
  }
 ]
}