apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-db-depl
  labels:
      name: nats-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-db
  template:
    metadata:
      labels:
        app: nats-db
        system: panda
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nats-db
          image: postgres:alpine
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_DB_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_DB_NAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nats-db-passwd-secret
                  key: NATS_DB_PASSWD
          volumeMounts:
            - name: nats-db-data
              mountPath: /var/lib/postgresql/data
              subPath: nats
      volumes:
        - name: nats-db-data
          persistentVolumeClaim:
            claimName: nats-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nats-db-srv
spec:
  type: ClusterIP
  selector:
    app: nats-db
  ports:
    - name: nats-db
      protocol: TCP
      port: 5432
      targetPort: 5432
